version: '3.8'

services:
  se-backend-product-sv:
    image: 13angs/se-backend-product-sv:latest
    build: 
      context: ../../../../backend
      dockerfile: apps/product-sv/Dockerfile
    networks:
      - se-network
    ports:
      - "5002:5000"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ServiceConfig__ServiceDiscoveryAddress=http://se-consul-server1:8500"
      - "ServiceConfig__ServiceAddress=http://se-backend-product-sv:5000"
      - "ServiceConfig__ServiceName=se-backend-product-sv"
      - "ServiceConfig__ServiceId=v1"
      - "RabbitMQ__HostName=amqp://guest:guest@se-rabbitmq-management:5672"

networks:
  se-network:
    name: se-network
    external: true