version: '3.8'

services:
  se-rabbitmq-management:
    image: 13angs/rabbitmq:3.11.3-management
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: se-rabbitmq-management
    hostname: se-rabbitmq-management
    ports:
      - target: 15672
        published: 15672

      - target: 5672
        published: 5672
    
    networks:
      - se-network

networks:
  se-network:
    external: true
    name: se-network