version: '3.8'

services:
  se-consul-server1:
    image: consul:latest
    container_name: consul-server1
    restart: always

    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=2"
    
    networks:
      - se-network
    
    volumes:
      - ./server1.json:/consul/config/server1.json:ro

  se-consul-server2:
    image: consul:latest
    container_name: consul-server2
    restart: always

    command: "agent -bootstrap-expect=2"
    
    networks:
      - se-network
    
    volumes:
      - ./server2.json:/consul/config/server2.json:ro


networks:
  se-network:
    name: se-network
    external: true