version: '3.8'

services:
  se-backend-comment-sv:
    image: 13angs/se-backend-comment-sv:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
      replicas: 2
    networks:
      - prod
    ports:
      - "5003:5000"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Production"
      - "RabbitMQ__HostName=amqp://guest:guest@se-rabbitmq-management:5672"
      - "ServiceConfig__ServiceDiscoveryAddress=http://consul-server:8500"
      - "ServiceConfig__ServiceAddress=http://se-backend-comment-sv:5000"
      - "ServiceConfig__ServiceName=se-backend-comment-sv"
      - "ServiceConfig__ServiceId=v1"

networks:
  prod:
    name: prod
    external: true