version: '3.8'

services:
  se-backend-comment-sv-01:
    image: 13angs/se-backend-comment-sv:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
      replicas: 1
      placement:
        constraints: [node.labels.rabbitmq01 == true]
    networks:
      - prod

    environment:
      - "ASPNETCORE_ENVIRONMENT=Production"
      - "RabbitMQ__HostName=amqp://admin:5af42315e38d@se-rabbitmq-management-01:5672"
      - "ServiceConfig__ServiceDiscoveryAddress=http://consul-server:8500"
      - "ServiceConfig__ServiceAddress=http://se-backend-comment-sv-01:5000"
      - "ServiceConfig__ServiceName=se-backend-comment-sv"
      - "ServiceConfig__ServiceId=01"
      # mongodb config
      - "MongodbConfig__ConnectionString=mongodb://root:9d08b3a2a423bc75@se-mongo-db:27017/"
      - "MongodbConfig__DatabaseName=comment_db"
      - "MongodbConfig__CollectionName=comments"

  se-backend-comment-sv-02:
    image: 13angs/se-backend-comment-sv:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
      replicas: 1
      placement:
        constraints: [node.labels.rabbitmq02 == true]
    networks:
      - prod

    environment:
      - "ASPNETCORE_ENVIRONMENT=Production"
      - "RabbitMQ__HostName=amqp://admin:5af42315e38d@se-rabbitmq-management-02:5672"
      - "ServiceConfig__ServiceDiscoveryAddress=http://consul-server:8500"
      - "ServiceConfig__ServiceAddress=http://se-backend-comment-sv-02:5000"
      - "ServiceConfig__ServiceName=se-backend-comment-sv"
      - "ServiceConfig__ServiceId=02"
      # mongodb config
      - "MongodbConfig__ConnectionString=mongodb://root:9d08b3a2a423bc75@se-mongo-db:27017/"
      - "MongodbConfig__DatabaseName=comment_db"
      - "MongodbConfig__CollectionName=comments"

networks:
  prod:
    name: prod
    external: true