version: '3.8'

services:
  se-backend-order-sv:
    image: 13angs/se-backend-order-sv:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
      replicas: 2
    networks:
      - prod
    environment:
      - "ASPNETCORE_ENVIRONMENT=Production"
      - "Services__ProductService=http://se-backend-product-sv:5000"
      - "ServiceConfig__ServiceDiscoveryAddress=http://consul-server:8500"
      - "ServiceConfig__ServiceAddress=http://se-backend-order-sv:5000"
      - "ServiceConfig__ServiceName=se-backend-order-sv"
      - "ServiceConfig__ServiceId=v1"
      # mongodb config
      - "MongodbConfig__ConnectionString=mongodb://root:9d08b3a2a423bc75@se-mongo-db:27017/"
      - "MongodbConfig__DatabaseName=order_db"
      - "MongodbConfig__CollectionName=orders"

networks:
  prod:
    name: prod
    external: true